---
version: '3.8'

services:

  zammad-backup:
    image: zammad-local

  zammad-init:
    image: zammad-local

  zammad-nginx:
    image: zammad-local

  zammad-railsserver:
    image: zammad-local

  zammad-scheduler:
    image: zammad-local

  zammad-websocket:
    image: zammad-local



  zammad-nginx:
    environment:
      - VIRTUAL_HOST=ticket.lopinga.at
      - NGINX_SERVER_SCHEME=https
    networks:
      - default
      - proxy_2_zammad

networks:
  proxy_2_zammad:
    external:
      name: proxy_2_apps
