---
version: "3.8"

services:
  zammad-nginx:
    environment:
      - VIRTUAL_HOST=ticket.lopinga.at
      - NGINX_SERVER_SCHEME=https
    networks:
      - default
      - proxy_2_zammad

networks:
  proxy_2_zammad:
    external:
      name: proxy_2_apps
